Import("env")

conf = Configure(env)
if conf.CheckCXXHeader("gemmi/mtz.hpp"):

    env.SharedLibrary(
        target="#/lib/dials_gemmi_mtz_ext",
        source=[
            "boost_python/gemmi_mtz.cc",
        ],
        LIBS=env["LIBS"],
    )
