repos:

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    args: [--safe, --quiet]
    files: \.pyi?$|SConscript$|^libtbx_config$
    types: [file]

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format
    files: \.c(c|pp|xx)?$|\.h(pp)?$

# Linting
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-comprehensions==3.8.0']

# Syntax check and some basic flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
