repos:

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    args: [--safe, --quiet]
    files: \.pyi?$|^libtbx_config$
    types: [file]

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

# Syntax check and some basic flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
