fast_hdf5_eiger_read: fast_hdf5_eiger_read.c \
	bitshuffle.c \
	lz4.c \
	bitshuffle_core.c \
	iochain.c
	h5cc -Wall -o fast_hdf5_eiger_read fast_hdf5_eiger_read.c \
	bitshuffle.c \
	lz4.c \
	bitshuffle_core.c \
	iochain.c

