
Import('env')

env.SharedLibrary(
  target='#/lib/dials_scratch_cctbx_cpp_examples_ext',
  source=['boost_python/array_gotchas.cc',
          'boost_python/debug_tools.cc',
          'boost_python/use_of_sparse.cc',
          'boost_python/examples_ext.cc'],
  LIBS=env["LIBS"])
